language: c

compiler:
  - gcc
  - clang

install:
  - cd ${TRAVIS_BUILD_DIR}
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
  - tar xf lcov_1.11.orig.tar.gz
  - ls
  - cd lcov-1.11/
  - sudo make install
  - cd ..
  - gem install coveralls-lcov
  - cd ${TRAVIS_BUILD_DIR}
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.2-Linux-x86_64.tar.gz
  - tar xf cmake-3.2.2-Linux-x86_64.tar.gz
  - ls
  - sudo cp -r cmake-3.2.2-Linux-x86_64/* /usr/local

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --zerocounters

script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./tests/morphytest

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info 'tests/*' '/usr/*' --output-file coverage.info
  - lcov --list coverage.info
  - coveralls-lcov --repo-token "DmbK0hPTO8S9QPraI4afrfqieeQnLpVpn" coverage.info
  - make clean

skip_cleanup: true
