language: c

compiler:
  - gcc
  - clang

install:
  - cd ${TRAVIS_BUILD_DIR}
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
  - tar xf lcov_1.11.orig.tar.gz
  - ls
  - sudo make -C ./lcov_1.11/ install
  - gem install coveralls-lcov

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --zerocounters

script:
  - cd ${TRAVIS_BUILD_DIR}
  - make debug test
  - ./tests/utest

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info 'tests/*' '/usr/*' --output-file coverage.info
  - lcov --list coverage.info
  - coveralls-lcov --repo-token ${COVERALLS_TOKEN}
  - make clean

skip_cleanup: true
